

GET http://localhost:8080/users/61718584216fadced5d98634

###

GET http://localhost:8080/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTcxODU4NDIxNmZhZGNlZDVkOTg2MzQiLCJpYXQiOjE2MzQ4MzE3NjZ9.uWZD0e3bavpsiHOAYQ4ViOFTnT7_qzJ6_t12vzBb2Z0

###

GET http://localhost:8080/users/byId/6164679799b75f798296c1d2

###

GET http://localhost:8080/users/6162e8dd4a878cace3596fec

###

POST http://localhost:8080/users
Content-Type: application/json

{
  "firstName": "Teacher",
  "lastName": "s",
  "email": "t1133@gmail.cl",
  "password":"password",
  "price": 20,
  "avatarId": "female_1",
  "userType": "teacher",
  "subjects": ["polish"],
  "connected": [{"_id": "123", "subject": "polish"}]
}

###

POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "t1133@gmail.cl",
  "password":"password"
}

###

PATCH http://localhost:8080/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
Content-Type: application/json

{
  "subjects": ["english"]
}

###
POST http://localhost:8080/users/connect/61647bb9c4e75187155063ec
Content-Type: application/json

{
  "_id": "61647d8877c05d2104e8642d",
  "subject": "english"
}

###
POST http://localhost:8080/users/disconnect/61647bb9c4e75187155063ec
Content-Type: application/json

{
  "_id": "61647d8877c05d2104e8642d",
  "subject": "english"
}

###

POST http://localhost:8080/messages
Content-Type: application/json

{
  "roomId": "6169395f3bd3943503f43474_61681e655c8c0353fa8b30e0",
  "from": "61681e655c8c0353fa8b30e0",
  "message": "siema 123"
}

###

DELETE http://localhost:8080/messages/617115bc1268b8030085abf6_6169395f3bd3943503f43474
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxNzFjNTdhMTViMTQ0Y2U0YzMzYTU1NCIsImZpcnN0TmFtZSI6IkJydW5vIiwibGFzdE5hbWUiOiJEemnEmWNpZWxza2kxIiwiZW1haWwiOiJicnVub2R6aTA3QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGF2aUxSSVBibGhvMHFRb1d6WnpQUy5jcmpDYVBwblVZbUtCYUNweUQvRUtSQmFZaG1TcXBhIiwicHJpY2UiOjY5LCJhdmF0YXJJZCI6ImZlbWFsZV8xIiwic3ViamVjdHMiOlsibWF0aCJdLCJ1c2VyVHlwZSI6InRlYWNoZXIiLCJfX3YiOjB9LCJpYXQiOjE2MzQ5OTIyODh9.HIKI9One01ieYydy2-rWHiysD5EIURvbl9WDjnYECp1


###

GET http://localhost:8080/users/chatted
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxNzFjNTdhMTViMTQ0Y2U0YzMzYTU1NCIsImZpcnN0TmFtZSI6IkJydW5vIiwibGFzdE5hbWUiOiJEemnEmWNpZWxza2kxIiwiZW1haWwiOiJicnVub2R6aTA3QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGF2aUxSSVBibGhvMHFRb1d6WnpQUy5jcmpDYVBwblVZbUtCYUNweUQvRUtSQmFZaG1TcXBhIiwicHJpY2UiOjY5LCJhdmF0YXJJZCI6ImZlbWFsZV8xIiwic3ViamVjdHMiOlsibWF0aCJdLCJ1c2VyVHlwZSI6InRlYWNoZXIiLCJfX3YiOjB9LCJpYXQiOjE2MzQ5OTIyODh9.HIKI9One01ieYydy2-rWHiysD5EIURvbl9WDjnYECp8