import ReactDOM from 'react-dom';

import App from './components/App';

const root = document.getElementById('root') as HTMLElement;

ReactDOM.render(<App />, root);

// TODO:
// DOKONCZYC SOCKETY (BLAD WYWALA, SOCKET NA TWORZENIE POKOJU (DO KAZDEGO I SPRAWDZIC CZY JEGO ID))
// W LISCIE NIE WYSWIETLAC DODANYCH NAUCZYCIELI
// WYSWIETLAC DOMYSLNIE NAUCZYCIELI Z WYBRANYCH PRZEDMIOTOW
// PROFIL
// PORTFEL
// OCENIANIE
// NA TELEFONY
// ?DODAWANIE PLIKOW / ZDJEC
// ?JAKIS PROSTY POKOJ Z KAMERKA (BARDZO PROSTY)

// SERVER:
// RATING
// WALLET
